@startuml DiagramaUML-Clases-TP2
hide circle
skinparam classAttributeIconSize 0

abstract Question{
    + id : long
    + options : List<GameOption>
    # correctOptions : List<GameOption>
    - calculatePoints(List<GameOptions>) : int
}

class GameOption{
    + id : long
	+ text : String
    + equals(Object obj) : Boolean
}

class OptionGroup{
    + options : List<GameOption>
}

class Score{
    + value : int
    - sumScore(Score score)
}

class Game{
    + players : List<Player>
	+ question : List<Question>
	+ currentPlayer : Player
    + start()
    + nextTurn(selectedOptions, selectedAugmenter)
    + getWinner()
}

class MatchResult{
    + player : Player
	+ selectedOptions : List<GameOption> 
	+ selectedAugmenter : AugmenterType 
    + sumMatchScoreToPlayer()
    + calculateForScoreAugmenter()
}

class ScoreCalculator{
    - {static} calculateAndAssignPoints(MatchResult p1Result,p2Result, question)
	+ checkAugmenters(MatchResult playerResult, Score p1Score, Score p2Score)
}

class Player{
    + name : String
	+ score : int
	+ augmentersUsesAvailable : Map<AugmenterType, Int>
    + answerQuestion(GameOption selectedOption) : MatchResult
    + answerQuestion(List<GameOption> selectedOption) : MatchResult
    + answerQuestionWithAugmenter(selectedOption, augmenter) : MatchResult
}

abstract ScoreAugmenter{
    + applyScoreAugmenter(currentPlayer, opponent, score, opponentScore)
    + substractUseOfAugmenter(player)
    - {abstract}applyScoreAugmenter(Score questionScore, Score opponentQuestionScore)
}


Game  --down>  Question
Game --down>  Player

OptionGroup --|> GameOption

ScoreCalculator --right> MatchResult
ScoreCalculator --> Question

MatchResult "1..1"*--up Player
MatchResult o-- ScoreAugmenter
MatchResult --> ScoreAugmenter

Player "1..1"*-- Score

Question "1..*"*--up GameOption

@enduml