@startuml DiagramaUML-Clases-TP2
hide circle
skinparam classAttributeIconSize 0

abstract Question{
    + id : long
    + options : List<GameOption>
    # correctOptions : List<GameOption>
    - calculatePoints(List<GameOptions>) : int
}

class GameOption{
    + id : long
	+ text : String
}

class OptionGroup{
    + options : List<GameOption>
}

class Score{
    + value : int
    - sumScore(Score score)
}

class Game{
    + players : List<Player>
	+ question : List<Question>
	+ currentPlayer : Player
}

class MatchResult{
    + player : Player
	+ selectedOptions : List<GameOption> 
	+ selectedAugmenter : AugmenterType 
}

class ScoreCalculator{
    - {static} calculateAndAssignPoints(MatchResult p1Result,p2Result, question)
	+ checkAugmenters(MatchResult playerResult, Score p1Score, Score p2Score)
}

class Player{
    + name : String
	+ score : int
	+ augmentersUsesAvailable : Map<AugmenterType, Int>
}

abstract ScoreAugmenter{
    + applyScoreAugmenter(currentPlayer, opponent, score, opponentScore)
    + substractUseOfAugmenter(player)
    - {abstract}applyNewScore(Player currentPlayer, Player opponent, int score, int opponentScore)
}


Game  --down>  Question
Game --down>  Player

OptionGroup --|> GameOption

ScoreCalculator --right> MatchResult
ScoreCalculator --> Question

MatchResult "1"*--up"1" Player
MatchResult o-- ScoreAugmenter

Player "1"*--"1" Score

Question "1"*--up"*" GameOption

@enduml