@startuml

actor User
title Diagrama Secuencia TP2 - Jugador contesta una pregunta
hide footbox

participant "player : Player" as player
participant "score : Score" as score
participant "noAugmenter : ScoreAugmenter" as noMultiplier

User -> player ** : new Player("Jugador1")

User -> player : answerQuestion\n(question, selectedOptionsPlayerN)
activate player

player -> noMultiplier** : new
player -> score : setAugmenter(noAugmenter) 

player -> Question : calculatePoints(selectedOption)

activate Question
Question --> player : points
deactivate Question

player -> score : setQuestionScore(points)
deactivate player

User -> ScoreCalculator : calculateAndAssignPoints(player ... playerN)
activate ScoreCalculator



ScoreCalculator -> ScoreCalculator : calculate(playerList)
activate ScoreCalculator
loop N players
loop N players
ScoreCalculator -> player : updateScore(opponentScore)
activate player
player -> score : update(opponentScore)
deactivate player
activate score
score -> noMultiplier : applyScoreAugmenter(this, opponentScore)
deactivate score

deactivate ScoreCalculator
end loop
end loop
deactivate ScoreCalculator

@enduml
