
@startuml

actor User
title Diagrama Secuencia TP2 - Prueba para pregunta True/False asignando puntaje a Jugador - Entrega 0
hide footbox


participant "question : Question" as question

participant "true : GameOption" as true
participant "false : GameOption" as false

participant "jugador1 : Player" as jugador1

User -> question ** : new TrueFalseQuestion
activate question
question --> User : question
deactivate question


User -> jugador1 ** : new Player("Jugador1")
activate jugador1
jugador1 --> User : jugador1
deactivate jugador1

User -> true ** : new GameOption("True")
activate true 
true --> User : true
deactivate true 

User -> false ** : new GameOption("False")
activate false
false --> User : false
deactivate false 

User -> question : setCorrectOption(false)
activate question
question -> question : correctOptions.add(false)
deactivate question

participant "match1 : MatchR" as match1

User -> match1 **: new MatchResult(jugador1, selectedOptionsPl1, null)
activate match1
match1 --> User : resultJugadorUno
deactivate match1 

User -> ScoreCalculator : calculateAndAssignPoints(match1, match2, question)
activate ScoreCalculator

participant "newScore : Score" as puntaje
ScoreCalculator -> question : calculatePoints
activate question
question --> ScoreCalculator : newScore
deactivate question

ScoreCalculator -> puntaje **: new Score(newScore)
activate puntaje
puntaje --> ScoreCalculator : newScore
deactivate puntaje

ScoreCalculator -> ScoreCalculator : checkAugmenters(match1, \nscorePlayer1, scorePlayer2)
activate ScoreCalculator
deactivate ScoreCalculator

ScoreCalculator -> match1 : getPlayer()
activate match1
match1 -> jugador1 : getScore()
activate jugador1
jugador1 -> jugador1 : sumScore(newScore)
deactivate jugador1
deactivate match1

deactivate ScoreCalculator

@enduml
@enduml