
@startuml

actor User
title Diagrama Secuencia TP2 - Pregunta Multiple Choice asgina puntajes a jugadores
hide footbox

participant "question : Question" as question

participant "true : GameOption" as true
participant "false : GameOption" as false

participant "jugadorN : Player" as jugadorN

User -> question ** : new TrueFalseQuestion

User -> true ** : new GameOption("True")
User -> false ** : new GameOption("False")

User -> question : setCorrectOption(false)
activate question
question -> question : correctOptions.add(false)
deactivate question

loop 2 Jugadores
User -> jugadorN ** : new Player("Jugador1")

participant "matchN : MatchR" as matchN

User -> jugadorN : answerQuestion(selectedOptionsPlayerN)
jugadorN -> matchN **: new MatchResult(jugadorN, \nselectedOptionsPlayerN)
jugadorN -> User : matchRN

end loop

User -> ScoreCalculator : calculateAndAssignPoints(matchN, match2, question)
activate ScoreCalculator

loop 2 Jugadores
participant "newScore : Score" as puntaje
ScoreCalculator -> question : calculatePoints
activate question
question --> ScoreCalculator : newScore
deactivate question

ScoreCalculator -> puntaje **: new Score(newScore)

ScoreCalculator -> ScoreCalculator : checkAugmenters(matchN, \nscorePlayer1, scorePlayer2)
activate ScoreCalculator
deactivate ScoreCalculator

ScoreCalculator -> matchN : getPlayer()
activate matchN
matchN -> jugadorN : getScore()
activate jugadorN
jugadorN -> jugadorN : sumScore(newScore)
deactivate jugadorN
deactivate matchN
end loop

deactivate ScoreCalculator

@enduml
